language: python
python:
- '2.7'
addons:
  apt:
    packages:
    - swig
    - libusb-1.0-0-dev
    - libprotobuf-dev
cache:
  pip: true
  apt: true
  directories:
  - $HOME/.cache/pip
env:
- TOXENV=py27
install:
- pip install tox coveralls
- pip install -e .
- wget https://github.com/google/protobuf/releases/download/v3.5.0/protoc-3.5.0-linux-x86_64.zip
- unzip protoc-3.5.0-linux-x86_64.zip
- sudo cp bin/protoc /usr/bin/protoc && sudo chmod 777 /usr/bin/protoc
- protoc --version
script: tox
after_success:
- coveralls
deploy:
  provider: pypi
  user: jettisonjoe
  on:
    tags: true
  password:
    secure: zFZNHtiht6OhCrbWMGGb+yBMmTJLKtAE5RiDl60m58Jx4t/UhMtHoC0+jtZ1hq2aeprfvw60zAIhB3HbLvb+E4Dcf9U8hEGDxJhMSMwGkXvFtrdAqce+I1YcNTXwCUApoJfE8Px1IZMRY9e1+u7r+cIWVggc3X97bWGGo+68A/ZkFxyGv75n8HRfCyHxK2hG/CGJWWmiK+fpDD68I3GbTyL1V5cRAkXNr4O1cSBDzeo0qOKzLZKAYR8M4SEQCz0Qlyatksa/p76ijF0tt5Q+kdVRANwlIltn57l43xwgL6ViOLs0rP19hlDITj5g6FZsNlRPPNxD5mUMuDEZefdcfm7sfvYHlU7hi38bxxWHXIbhUg6147V1+1oVu+dcxpv6/LgbYKSF2rxmkB6pZLlvOKK/U8Ni+3cN5KO1IumBdtQPDvSVUnsEB6GiVazm5xdR5fHvrIJaIHeAb0CBVlU1mnpHU0qUhAp3NcVHQtDM+ykcKvxjtNptRLp3o2AfTEPQmOHdG5KX21L69vagUWrwHf9mjxyQn6XfuzChj5W+fOcTlvHENK1Z8+KZg3a9sIhTFCPBxB4eX4TlUqS9HIndZFuiiDMszysJMZZ6wDDsUvlpdgHpSJlAmCoDd7cwjDWrTD//O3jRyYTbZTSFHpDRI/McnWJ7v8zYP0rlOQRqTb0=
